### PR TITLE
Rewards updates

### PR DESCRIPTION
**Pull request by goslingo**

### CODE REVIEW

**Comment by neildawson** [comment]
Unsolicited feedback

- Can we remove days, hours, and minutes when they reach zero? e.g.
  - "0d 1h 12m 48s" → "1h 12m 48s"
  - "0h 12m 48s" → "12m 48s"
  - "0m 48s" → "48s"
- "Rewards I've earned" link has got a really big clickable area underneath
- Is it possible to prevent the arrow on these links from breaking onto a new line without at least the final word from the link? 🤔

**Comment by Ben-peoplemake** [comment]
@goslingo Few notes:
 The Call to get the epoch data is failing because of missing CORS headers

image

-  Is it supposed to be APY or is it API?

- Should "Loading..." disappear after we show the message "Can't fetch APY right now..."?

- Is there a retry for the call at all? Would we want one?

**Comment by goslingo** [comment]
APY calculations have been fixed.
Links have been updated.

**Review by JonRay15 — APPROVED** [review]
Approved

**Pull request merged**
