### PR TITLE
Create interstitial page to route external links through

### PR DESCRIPTION
**Pull request by goslingo**
- Created a new page '/external-link' that takes a 'url' parameter and redirects the user to that url in 10 seconds.
- Created a convenience function to modify a link to reroute through this new interstitial page.

For example:
```
<Link to={routeThroughInterstitialPage(link)}>This link will be routed through the interstitial page</Link>
```

The page can be tested by clicking on any of the three blocks in the hero area of the home page:

Screenshot 2022-12-06 at 14 14 37

Preview link for testing: https://deploy-preview-395--vega.netlify.app/

### CODE REVIEW

**Comment by Ben-peoplemake** [comment]
@goslingo I'm not sure if it is a netlify thing. But when I click the link to go to the URL rather than letting the countdown finish, it opens in a new tab rather than the current one.

Then the countdown will finish on the redirect page and take me to the new URL in that tab. (So I end up with two tabs of the new URL)

**Comment by campbellssource** [comment]
comment (non-blocking): I wonder if it should be specifically leaving Vega.**xyz** because you might be still going to a Vega thing

**Comment by campbellssource** [comment]
tested with a ipsf: redirect ✅✅✅

**Comment by edd** [comment]
An issue with the URL based passing of the destination link is that it's easy to make a malicious version. For fun, I could link this on telegram:
https://deploy-preview-395--vega.netlify.app/external-link/?url=https://dweb.link/ipfs/QmcniBv7UQ4gGPQQW2BwbD4ZZHzN3o3tPuNLZCbBchd1zh as a link to the block explorer, but the people who follow that link will be given up, let down and deserted.

The first solution that springs to mind is an allow list of URLs. But then, how does that allow list get populated when a new build of explorer goes up? 🤔

**Comment by goslingo** [comment]
> An issue with the URL based passing of the destination link is that it's easy to make a malicious version. For fun, I could link this on telegram: https://deploy-preview-395--vega.netlify.app/external-link/?url=https://dweb.link/ipfs/QmcniBv7UQ4gGPQQW2BwbD4ZZHzN3o3tPuNLZCbBchd1zh as a link to the block explorer, but the people who follow that link will be given up, let down and deserted. If I wanted to put more effort in and fork console but have it submit subtly incorrect orders, deployed that to IPFS and did it, then we've just created what looks like an official link to a malicious thing.
> 
> The first solution that springs to mind is an allow list of URLs. But then, how does that allow list get populated when a new build of explorer goes up? 🤔

It's a very good point... however to counter this, people will immediately see the message that they are leaving vega.xyz and moving to a non-Vega hosted link. It's quite an explicit message.

While we could take the approach of maintaining a list of allowed URLs, wouldn't we be inadvertently endorsing them in some way by the fact we 'allow' them?

Interested to hear what others think too, I'm open to either approach, or other ideas!

**Comment by campbellssource** [comment]
This was discussed a little in a meeting. notes:
The website can link to something like: https://console-fairground-wtf.ipns.dweb.link/ and it'll do the job of serving the latest version of Console. Therefore the generic solution on the website may not be needed. 

Decision: don't merge this PR but instead have a redirect page that does not take any parameter but is hard coded to any of the places like https://console-fairground-wtf.ipns.dweb.link/ OR refine this PR so that it will only work for links that are on the whitelist.

**Comment by goslingo** [comment]
@campbellssource

I've updated the way this works:

- There is a [whitelist file](https://github.com/vegaprotocol/vega.xyz/blob/390-create-redirect-page/interstitial-allow.json) in the root folder
- Only whitelisted URLs will show the interstitial page and be redirected
- Any other URLs will be hit with the 404 page

You can test this by clicking on 'Console' on the home page hero blocks. This URL is whitelisted and goes to the interstitial page.

If you click on the other two blocks, 'Governance' and 'Block Explorer', these are not whitelisted and will show the 404 page.

**Comment by pennyandrews** [comment]
I've had a look and think this now works as agreed so I have approved, however I'm not sure we are all aligned on what we should be applying it to once we push it live... I think it's just console as that is the only thing right now that is hosted on IPFS and therefore genuinely not hosted by Vega. But I'd like someone else to verify if this is correct :) @campbellssource @ckpringle ?

**Comment by Ben-peoplemake** [comment]
@goslingo Just noticed that if you are using the light theme and go to the redirect you can't read any of the text. Screen recording attached.
https://user-images.githubusercontent.com/117179940/212150235-c57a5201-d6f1-439d-b25e-abaea9b426ed.mov

**Comment by barnabee** [comment]
I'm not sure we should be showing the interstitial for governance (token) site or block explorer, those *are* hosted by us.

**Comment by goslingo** [comment]
> I'm not sure we should be showing the interstitial for governance (token) site or block explorer, those _are_ hosted by us.

The interstitial page only shows for console, the other links you mention click through directly.

**Review by pennyandrews — APPROVED** [review]

**Pull request merged**
